# Azure DevOps pipeline template used to build bundle.
parameters:
  - name: 'api_host'
    type: string
    default: ''

  - name: 'env'
    type: string
    default: ''

  - name: 'cdn_logos'
    type: string
    default: ''

  - name: 'assistance_link'
    type: string
    default: ''

  - name: 'show_status_info'
    type: boolean
    default: false

  - name: 'checkout_host'
    type: string
    default: ''

steps:
- bash: |
    chmod +x env.sh
    env -i \
      ARC_FE_APIHOST=${{ parameters.api_host }} \
      ARC_FE_ENV=${{ parameters.env }} \
      ARC_FE_ENTITIES_LOGO_CDN=${{ parameters.cdn_logos }} \
      ARC_FE_ASSISTANCE_LINK=${{ parameters.assistance_link }} \
      ARC_FE_SHOW_STATUS_INFO=${{ parameters.show_status_info }} \
      ARC_FE_CHECKOUT_HOST=${{ parameters.checkout_host }} \
      bash env.sh

  displayName: 'Populate environment file'
