name: 'coverage'
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - run: yarn install
      - run: yarn generate
      - uses: ArtiomTr/jest-coverage-report-action@c026e98ae079f4b0b027252c8e957f5ebd420610 # v2
        with:
          package-manager: yarn
          test-script: yarn jest
