name: Deploy Storybook (develop) on GH Pages

on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@b75ece8f984a32b2adb322065d7a8a2cc8db2d52 # v1.0.3
        with:
          install_command: yarn install
          build_command: yarn build-storybook -o storybook-static
          path: storybook-static
