name: Deploy Storybook (develop) on GH Pages
on:
  push:
    branches:
      - 'develop'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: yarn install
          build_command: yarn build-storybook -o storybook-static
          path: storybook-static
