name: 'PR title check'
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@860e8dc639f8e60335a6f5e8936ba67ed2536890 # v4.3.0
        with:
          regexp: '((feat|fix|chore|ci|test|build|docs|perf|refactor|breaking): \[P4PU(-[0-9]{2,4})?\] .+)|(Bump .+)|(Pin dependencies)'
          helpMessage: "Example: 'feat: [P4PU-1041] example of title'"
