name: 'PR title check'
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: '(feat|fix|chore|breaking): \[P4PU(-[0-9]{2,4})?\] .+'
          helpMessage: "Example: 'feat: [P4PU-1041] example of title'"
